#!/bin/bash
echo "PREPRINT -- vytvorenie parnych a neparnych stranok"
echo "Vstup :" $1 "Vystup:" parne.ps neparne.ps
if test $2 -a $2 = "m" ; then
echo "Zvacsenie : 1200"
dvips -x 1200 -o /tmp/tmp.ps $1
else
dvips -o /tmp/tmp.ps $1
fi
psbook /tmp/tmp.ps | psnup -2 | psselect -e > neparne.ps
psbook /tmp/tmp.ps | psnup -2 | psselect -o > parne.ps
rm /tmp/tmp.ps













