#!/bin/bash

STAT=`echo $1 | grep '^[[:upper:]]\{4\}'`
DD=`echo $2 | cut -f1 -d- | grep '^[[:digit:]]\{2\}$'`
MM=`echo $2 | cut -f2 -d- | grep '^[[:digit:]]\{2\}$'`
YYYY=`echo $2 | cut -f3 -d- | grep '^[[:digit:]]\{4\}$'`

if test  "$#" != "2"  -o  -z "$DD"  -o  -z "$MM" -o  -z "$YYYY" 
then
	echo "Usage: metar station dd-mm-yyyy"
	exit 1
fi

curl -s 'http://www.ogimet.com/display_metars2.php?lang=en&lugar='$STAT'&tipo=SA&ord=REV&nil=SI&fmt=txt&ano='$YYYY'&mes='$MM'&day='$DD'&hora=00&anof='$YYYY'&mesf='$MM'&dayf='$DD'&horaf=23&minf=59&send=send' | 
	tr -d '\n' |
	sed 's:.*<pre>\(.*\)</pre>.*:\1:' | sed 's/=/=\n/g' | grep -v '#' | sed 's/ \+/ /g'



