#!/usr/bin/env python
import sys
import dateutil.parser
inp=sys.stdin.readline()
ident,value=inp.split(":")
value=dateutil.parser.parse(value,dayfirst=True).strftime("%Y-%m-%d")
print "%s: %s" % (ident,value)

