#!/usr/bin/env python3
import sys
import re
line=sys.stdin.readline().strip()
print(r'\begin{pmatrix}')
lines_out=[]
for row_s in re.findall(r'{[^}]*}',line):
    numbers=re.findall(r'[0-9.\-a]+',row_s)
    lines_out.append('&'.join(numbers))
print((r'\\'+'\n').join(lines_out))
print(r'\end{pmatrix}')


